notifications:
    email: false
    slack: itage:bcU8Wypogj7TqOJv0y7mCk1j

language: go

before_install:
    - sudo apt-get install -y coffeescript
    - make -j4

go:
    - tip
cache:
    - apt: true
